
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS font_size TEXT DEFAULT '16px',
ADD COLUMN IF NOT EXISTS default_video_quality TEXT DEFAULT 'Auto',
ADD COLUMN IF NOT EXISTS data_saver_mode BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS autoplay_limit INTEGER DEFAULT 10;
