ALTER TABLE reels ADD COLUMN IF NOT EXISTS dubbed_audio_url TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS dubbed_audio_url TEXT;
ALTER TABLE reels ADD COLUMN IF NOT EXISTS is_dubbing_active BOOLEAN DEFAULT FALSE;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS is_dubbing_active BOOLEAN DEFAULT FALSE;
